import { Inter } from "next/font/google";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Shopify + Next.js 13!"
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
       <ChakraProvider>
      <body className={inter.className}>{children}</body>
      </ChakraProvider>
    </html>
  );
};

export default RootLayout;